services:
  postgres:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  # strapi:
  #   image: elestio/strapi-${NODE_ENV}:latest
  #   restart: always
  #   env_file: .env
  #   volumes:
  #     - ./strapi/config:/opt/app/config
  #     - ./strapi/api:/opt/app/src/api
  #     - ./.env:/opt/app/.env
  #   ports:
  #     - "1337:1337"
  #   depends_on:
  #     - postgres

  strapi:
    image: ghcr.io/sehrgutesoftware/strapi-dockerized:latest
    restart: always
    env_file: .env
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/api:/opt/app/src/api
      - ./strapi/components:/opt/app/src/components
      - ./.env:/opt/app/.env
    depends_on:
      - postgres
    command: ["npm", "run", "develop"]

  web:
    build: .
    restart: always
    depends_on:
      - strapi

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - strapi

volumes:
  postgres-data:
