services:
  postgres:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

  strapi:
    image: ghcr.io/sehrgutesoftware/strapi-dockerized:latest
    restart: always
    env_file: .env
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/api:/opt/app/src/api
      - ./strapi/components:/opt/app/src/components
      - ./.env:/opt/app/.env
    ports:
      - "1338:1337"
    depends_on:
      - postgres
    command: ["npm", "run", "develop"]

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - strapi

volumes:
  postgres-data:
